### ISSUE TITLE
Problem when migrating project from UE 5.4 to 5.5 (The Solution!)

### ISSUE THREAD

**Issue by O-Tire** [UnrealSharp/UnrealSharp#359]
### **This is a guide for people who can't get UnrealSharp working after converting their project to UE 5.5**
If you have installed Unreal Engine 5.5 and trying to migrate your project but you are getting compilation errors, missing namespaces or your project can't be opened, this short step-by-step guide is for you.

1. Install Unreal Engine 5.5.
2. Make sure to take a backup of you project before continuing.
3. Go to your project's directory and remove 'UnrealSharp-main' from 'Plugins'.
4. Right click on the .uproject and select 'Switch Unreal Engine version...' and choose 5.5.
5. Run the .uproject to convert it. After converting it you might see some missing parent class errors; don't worry about them.
6. Download the latest version of UnrealSharp from GitHub and extract the zip file inside your project's 'Plugins' folder.
7. Make sure you have .NET 9.0 installed. There might be some communication issues between the ProjectGlue and UnrealSharp if you are using an older .NET version.
8. Run the .uproject once again to compile the plugin. The plugin should compile successfully but after that UE will try to open your project which will probably result in an error. This is normal for now.

-=-=-=-=-=-=-=-=-=-= It will get a bit difficult from this point forward

9. Create a new Unreal Engine 5.5 project, install UnrealSharp on it, open the newly created project and create a new C# project from Unreal Editor for it.
10. Close Unreal Editor and copy the Script/ProjectGlue and replace (delete and readd) your real project's ProjectGlue with it.
11. Open the .sln file in the 'Script' folder of your real project.
12. You will see two C# projects in the solution; one is the ProjectGlue, and the other one is named after your game. From now on, we will call that MyScripts.
13. Change the .NET versions of ProjectGlue and MyScripts to 9.0 (the way you do that depends on your IDE or text editor)
14. Then replace the assembly references that ProjectGlue and MyScript have, with the newly created UnrealSharp.dll that is located in "Plugins\UnrealSharp-main\Binaries\Managed\net9.0" (this also depends on your IDE)
15. Make sure MyScripts has a reference to the ProjectGlue

-=-=-=-=-=-=-=-=-=-= The hard part is done!

16. Now, your project should not have any errors in the ProjectGlue and no errors related to namespaces in MyScripts.
17. However now MyScripts probably has some errors related to missing functions. In the newest version of UnrealSharp, many functions have been replaced with properties. For example, GetActorTransform() is now ActorTransform. Also, UEnums should now have an underlying type of byte or whatever that means! Just add a ': byte' after your UEnums' names to fix any errors that are related to them. 

Now after fixing your code, your project should compile successfully in the new version of Unreal Engine! Thanks for following this guide. Feel free to ask your questions.

**Comment by OlssonDev** [comment]
This is a very extensive guide, this should not be needed. I upgraded a project yesterday from 5.4 to 5.5 without any issues. 

When did you last update the plugin when you upgraded to 5.5? Because the GetActorTransform => ActorTransform was a commit from a long time ago, even before we upgraded to .NET9

**Comment by O-Tire** [comment]
> This is a very extensive guide, this should not be needed. I upgraded a project yesterday from 5.4 to 5.5 without any issues.
> 
> When did you last update the plugin when you upgraded to 5.5? Because the GetActorTransform => ActorTransform was a commit from a long time ago, even before we upgraded to .NET9, which seems to be the main issue here.
> 
> > Compile the plugin as any other Unreal Engine plugin using the IDE of your choice.
> 
> As the setup guide says, I don't recommend using the plugin without a C++ solution, running it from .uproject comes with a lot of caveats.

Yes, my UnrealSharp version was very old before upgrading to the new one. I should remove that part from the guide.
The reason this is so extensive is because the C# solution couldn't communicate with the plugin at all. So, there was a lot of manual changes that had to be done.
